### ISSUE TITLE
Having some UnicodeDecodeError errors using csvdedupe

### ISSUE THREAD

**Issue by AlJohri** [dedupeio/csvdedupe#39]
Here's the traceback for the UnicodeDecodeError I was running into.

UnicodeDecodeError

```
Traceback (most recent call last):
  File "/Users/johria/.pyenv/versions/3.5.0/bin/csvdedupe", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/Users/johria/.pyenv/versions/3.5.0/lib/python3.5/site-packages/csvdedupe/csvdedupe.py", line 161, in launch_new_instance
    d = CSVDedupe()
  File "/Users/johria/.pyenv/versions/3.5.0/lib/python3.5/site-packages/csvdedupe/csvdedupe.py", line 33, in __init__
    self.input = open(self.configuration['input'], 'rU').read()
  File "/Users/johria/.pyenv/versions/3.5.0/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 546689: invalid continuation byte
```

In case it means anything, I opened the file with excel and first saw this error message:

> Alert
> Excel has detected that 'DC_contribs_since_2007.csv' is a SYLK file, but cannot load it. Either the file has errors or it is not a SYLK file format. Click OK to try to open the file in a different format.

After opening the file in Sublime and doing File -> Save with Encoding -> UTF-8, everything worked.

Not sure if you have any ideas regarding what happened, but thought I'd drop an issue!

The file I was working with is this one: https://github.com/codefordc/dc-campaign-finance-watch/blob/develop/DC_contribs_since_2007.csv

**Comment by DaveKlassen4** [comment]
I worked around this issue by just eliminating all unicode characters

**Comment by DaveKlassen4** [comment]
I found these gems today, that state unicode is supported in python3:

     https://groups.google.com/forum/#!searchin/open-source-deduplication/unicode/open-source-deduplication/9NMkr5r7t-0/xPGb8Q0OYpwJ

Looking at this file:

     https://github.com/datamade/csvdedupe/blob/master/setup.py

at line 8, if we are using python3, we should install the following python package:

     pip3 install unicodecsv

**Comment by fgregg** [comment]
Python 3's csv module already handles unicode, we just need the `unicodecsv` for python2. 

However, handling different encodings of the file could definitely be more robust. Probably the right thing to do is to add chardet http://chardet.readthedocs.org/en/latest/usage.html
