### ISSUE TITLE
cannot import name 'SIGPIPE'

### ISSUE THREAD

**Issue by r0f1** [dedupeio/csvdedupe#51]
Hi, I have written the following code:

```
from csvdedupe import csvlink
```

and get the exception 

```
ImportError was unhandled by user code
cannot import name 'SIGPIPE'
```

I am under Windows 7 and using Visual Studio 2015, Version 14 and Python Version 3.5.
I already tried [this](http://www.chiark.greenend.org.uk/~cjwatson/blog/python-sigpipe.html) solution but it didn't work since `signal` does not appear to have the member `SIGPIPE`.

Is there a way to fix this?
Thank you.

**Comment by fgregg** [comment]
Try removing these lines, and let me know if that works. https://github.com/datamade/csvdedupe/blob/master/csvdedupe/csvhelpers.py#L10-L11

Sorry, I don't have a windows machine so I'm not really able to effective develop on them.

**Comment by micbster** [comment]
change that line from:

1.  Change the lines in csvhelpers.py:

import sys
from signal import signal, SIGPIPE, SIG_DFL

to:

import sys

2. and remove this line:

signal(SIGPIPE, SIG_DFL)

**Comment by SasySaa** [comment]
Hi i'm using csvdedupe on Windows 7  for a simple linkage of two csv files but there is a problem with csvdedupe. I have installed phyton 3.6,visual studio,btrees and other csvdedupe dependencies but the program give me this error.
I alredy tried the micbster solution but doesn't work for me
![screenshot_1](https://cloud.githubusercontent.com/assets/24788697/24999837/5dc8607c-203f-11e7-8f3c-650aa28d323e.jpg)
.
Someone can help me with the right commands sequence to link the csv's files on BASH of Windows?

(In the screenshot i've just tried to dedupe the example but didn't work nothing).

**Comment by sterlingpetersen** [comment]
Ran into the same issue. Removing these lines works:
https://github.com/datamade/csvdedupe/blob/master/csvdedupe/csvhelpers.py#L10-L11

@SasySaa Try opening the csvhelpers.py file on your computer and deleting the lines specified above. On your computer, it appears to be located at 
"C:\Users\TadFamily\AppData\Local\Programs\Python\Python36\Lib\site-packages\csvdedupe\csvhelpers.py"
