### ISSUE TITLE
Getting this error after completing the training.  "SystemError: Negative size passed to PyBytes_FromStringAndSize"

### ISSUE THREAD

**Issue by brandonlipman** [dedupeio/csvdedupe#67]
Here is the terminal output. I have not changed any code from what was given. 

```python
Traceback (most recent call last):
  File "csv_example.py", line 151, in <module>
    threshold = deduper.threshold(data_d, recall_weight=1)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dedupe/api.py", line 237, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dedupe/api.py", line 68, in thresholdBlocks
    probability = core.scoreDuplicates(self._blockedPairs(blocks),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dedupe/api.py", line 248, in _blockedPairs
    block, blocks = core.peek(blocks)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dedupe/core.py", line 279, in peek
    record = next(records)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dedupe/api.py", line 281, in _blockData
    for block in viewvalues(blocks):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_collections_abc.py", line 693, in __iter__
    for key in self._mapping:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

**Comment by brandonlipman** [comment]
@fgregg I am on macOS Sierra 10.12.4.

**Comment by fgregg** [comment]
@brandonlipman  can you paste the output of this (running python3)

```python
import shelve
d = shelve.open('f')
import dbm
print(dbm.whichdb('f'))
```

**Comment by brandonlipman** [comment]
@fgregg Yes. I get the following:
`None`
![screenshot 2017-05-10 13 40 28](https://cloud.githubusercontent.com/assets/4401127/25912734/50f7e3ca-3586-11e7-8656-e971b29272f3.png)

**Comment by fgregg** [comment]
could you clone https://github.com/dedupeio/dedupe and then `dedupe` library run 

`python tests/canonical.py`

and let me know if you get the same error?

**Comment by brandonlipman** [comment]
@fgregg That worked. Any idea why the samples are not working or could I use `canonical.py`as a template?
<img width="1107" alt="screenshot 2017-05-10 18 10 07" src="https://cloud.githubusercontent.com/assets/4401127/25923540/f21f47f0-35ab-11e7-8353-3a279b9deb0d.png">

**Comment by fgregg** [comment]
Hrmm.. no, I don't yet understand why it's working in one place and not the other.

**Comment by brandonlipman** [comment]
@fgregg Yes, seems a little odd. Let me know what else you need from me and I would be happy to help. Really would love to use this in a project I am working on where duplication is running rampant.

**Comment by fgregg** [comment]
would it be possible to do some screensharing. I'm not able to reproduce this.

**Comment by fgregg** [comment]
would it be possible to do some screensharing. I'm not able to reproduce this.

**Comment by brandonlipman** [comment]
@fgregg Most definitely. Feel free to email me brandon@lipmanb.com I am available most of the day.

**Comment by brandonlipman** [comment]
@fgregg Let me know if you have time this week. Thanks!

**Comment by fgregg** [comment]
Let's whittle down this script until we get a minimum test case:

```
import random
import shelve
import pickle
import os
import tempfile

fd, file_path = tempfile.mkstemp()
os.close(fd)

try:
    shelf = shelve.open(file_path, 'n',
                        protocol=pickle.HIGHEST_PROTOCOL)
except Exception as e:
    if 'db type could not be determined' in str(e):
        os.remove(file_path)
        shelf = shelve.open(file_path, 'n',
                            protocol=pickle.HIGHEST_PROTOCOL)


record = {'foo' : 'bar'}
ids = set(range(1000))
        
for i in range(10000):
    k = str(random.randrange(1000))
    if k in shelf:
        shelf[k] += [(i, record, ids)]
    else:
        shelf[k] = [(i, record, ids)]

for block in shelf.values():
    if len(block) > 1:
        print(block)
```

**Comment by fgregg** [comment]
@tendres, @motrippy, it'd be great if you could help isolate this error.

**Comment by tendres** [comment]
Running the above script returns the following:

```
HASH: Out of overflow pages.  Increase page size
Traceback (most recent call last):
  File "/Users/tendres/PycharmProjects/dedupe/tests/test_shelve.py", line 25, in <module>
    shelf[k] += [(i, record, ids)]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database

Process finished with exit code 1
```

**Comment by fgregg** [comment]
@tendres, fun! 

Can you try reducing the size of ids and see if you can reproduce the `Negative size passed to PyBytes_FromStringAndSize` errors. I'm trying to get a minimal test case for https://bugs.python.org/issue30388

**Comment by tendres** [comment]
@fgregg 
ids = set(range(525)) = runs and exits code 0
ids = set(range(530)) = strange - 50/50 runs and exits code 0  or exits with:
```
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
```
Hope that is useful. Let me know if I can help - free today.

**Comment by fgregg** [comment]
hi @tendres, let's deal with this _dbm.error later. Right now I want to try to isolate the `negative size` error. 

You get that `negative size` error when you run csv_example.py?

@tendres, @brandonlipman, if you could join me on https://webchat.freenode.net/?channels=dedupe that would be great

**Comment by tendres** [comment]
@fgregg  yes - still getting the `negative size`error with the csv_example.py.
I am on the dedupe channel.

**Comment by tendres** [comment]
@fgregg still messing around with this - within PyCharm, when I run in debug mode or with coverage the csv_example.py works consistently. A vanilla run is a crap shoot - something must be getting ahead of itself that is slowed down by the former. I am on webchat all day.

**Comment by fgregg** [comment]
@tendres @brandonlipman @motrippy, 

can you please run 

```
otool -L $(python3.6 -c 'import _dbm;print(_dbm.__file__)')
```
on the command line and paste your output in this thread.

**Comment by tendres** [comment]
Running python3.5 so:

otool -L $(python3.5 -c 'import _dbm;print(_dbm.__file__)')

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload/_dbm.cpython-35m-darwin.so:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0,
current version 125.2.0)





  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=endres.thomas@gmail.com&idSignature=22>

**Comment by tendres** [comment]
Upgraded to 3.6:

otool -L $(python3.6 -c 'import _dbm;print(_dbm.__file__)')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_
dbm.cpython-36m-darwin.so:

/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version
125.2.0)

**Comment by tendres** [comment]
copy/paste issues

otool -L $(python3.6 -c 'import _dbm;print(_dbm.__file__)')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_
dbm.cpython-36m-darwin.so:

/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version
125.2.0)

**Comment by liufuyang** [comment]
I am having the same issue, and I have the same output of the command mentioned above:
```
/Users/fuyangliu/python3.5-env/lib/python3.5/lib-dynload/_dbm.cpython-35m-darwin.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.0)
```
