### ISSUE TITLE
Reusing Training Data?

### ISSUE THREAD

**Issue by alixaxel** [dedupeio/csvdedupe#76]
Great tool!!! 👏

I'm currently using `csvlink` to, well, link CSV files. :)

I have a `canonical.csv` file that contains a list of manually curated product names and attributes. Besides that file, I have a bunch of other `store[XYZ].csv` files that also contain a list of products, but in a much messier and inconsistent format. The headers/columns are the same in all the files, even if empty.

My goal is to run `csvlink` to map as many products as possible from stores to `canonical` IDs:

```
csvlink canonical.csv storeX.csv --output_file storeX_curated.csv --field_names name brand model color --skip_training --training_file training.json
csvlink canonical.csv storeY.csv --output_file storeY_curated.csv --field_names name brand model color --skip_training --training_file training.json
csvlink canonical.csv storeZ.csv --output_file storeZ_curated.csv --field_names name brand model color --skip_training --training_file training.json
```

Since a lot of the individual stores will share common terms with the others, I wonder if it's possible to reuse the training data across several stores. Or do I have to maintain a `training.json` file for every store pair?

**Comment by fgregg** [comment]
you can use a training json file wherever you like, as long as it is consistent with the data model (i.e. all the fields mentioned the the datamodel are in the training data)
