### ISSUE TITLE
Load custom comparators on the fly

### ISSUE THREAD

**Issue by gmile** [dedupeio/csvdedupe#78]
It would be super-helpful to be able to load custom written comparators on the fly from `.py` files. Otherwise I have to basically fork `csvdedupe` to add some throwaway comparator functions.

One way I see it this:

* specifying a path to single file:

    ```
    csvdedupe /tmp/persons.csv \
      --field_names first_name last_name email \
      --output_file /tmp/persons_output.csv
      --comparators_path /tmp/comparators.py
    ```

* specifying a path to folder:

    ```
    csvdedupe /tmp/persons.csv \
      --field_names first_name last_name email \
      --output_file /tmp/persons_output.csv
      --comparators_path /tmp/comparators/
    ```

**Comment by fgregg** [comment]
I think this goes beyond the relatively simple interface I want for csvdedupe. Thanks for the suggestion!
