### ISSUE TITLE
AttributeError: 'CSVDedupe' object has no attribute 'field_def'

### ISSUE THREAD

**Issue by ysfdc** [dedupeio/csvdedupe#81]
In the following line, it references a member that doesn't exist:
```
self.field_names = [self.field_def['field']
                                for field_def in self.field_definition]
```

Should be
```
self.field_names = [field_def['field']
                                for field_def in self.field_definition]
```

**Comment by lw334** [comment]
same error!

**Comment by lw334** [comment]
@fgregg

**Comment by sskadamb** [comment]
Is this change updated in `pip`? I still see: 

`self.field_names = [self.field_def['field'] 
                                for field_def in self.field_definition]`

**Comment by ghost** [comment]
@fgregg @reidab This change doesn't appear to have made it to PyPI. I have 0.1.20, but I still get this error.

EDIT: Sorry, I was wrong. I had to uninstall and reinstall before my system picked up the changes in the new version.
